<?php

namespace Database\Seeders;

use App\Models\ModulePermission;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/**
 * Giving Statements Module Permission Seeder
 * 
 * Creates all necessary permissions for the giving_statements module.
 * These permissions are tied to the module and will be available
 * when the module is active.
 */
class GivingStatementsPermissionSeeder extends Seeder
{
    /**
     * Module key for giving statements
     */
    private const MODULE_KEY = 'giving_statements';

    /**
     * Permission definitions for the module
     */
    private const PERMISSIONS = [
        [
            'permission_key' => 'view',
            'name' => 'View Giving Statements',
            'description' => 'Access the giving statements dashboard and view reports',
            'level' => 'basic',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'generate',
            'name' => 'Generate Giving Statements',
            'description' => 'Create new giving statements for members',
            'level' => 'basic',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'download',
            'name' => 'Download Giving Statements',
            'description' => 'Download generated giving statement PDFs',
            'level' => 'basic',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'email',
            'name' => 'Email Giving Statements',
            'description' => 'Send giving statements via email to members',
            'level' => 'basic',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'bulk_email',
            'name' => 'Bulk Email Giving Statements',
            'description' => 'Send statements to multiple members at once',
            'level' => 'advanced',
            'is_premium' => true,
        ],
        [
            'permission_key' => 'configure',
            'name' => 'Configure Giving Statements',
            'description' => 'Manage settings, email templates, and password policies',
            'level' => 'advanced',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'view_all_reports',
            'name' => 'View All Reports',
            'description' => 'View giving statements generated by other users',
            'level' => 'advanced',
            'is_premium' => false,
        ],
        [
            'permission_key' => 'delete_reports',
            'name' => 'Delete Reports',
            'description' => 'Delete generated giving statement records',
            'level' => 'premium',
            'is_premium' => true,
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Creating Giving Statements module permissions...');

        foreach (self::PERMISSIONS as $index => $permissionData) {
            $this->createPermission($permissionData, $index);
        }

        $this->command->info('Giving Statements permissions created successfully!');
    }

    /**
     * Create a single permission
     */
    private function createPermission(array $data, int $sortOrder): void
    {
        $permissionKey = self::MODULE_KEY . '.' . $data['permission_key'];
        $name = $data['name'];

        // 1. Create Spatie Permission (for role-based access control)
        $spatiePermission = Permission::firstOrCreate(
            ['name' => $name],
            ['guard_name' => 'web']
        );

        // 2. Create Module Permission (for module-specific access control)
        ModulePermission::firstOrCreate(
            [
                'module_key' => self::MODULE_KEY,
                'permission_key' => $data['permission_key'],
            ],
            [
                'name' => $name,
                'description' => $data['description'],
                'level' => $data['level'],
                'is_premium' => $data['is_premium'],
                'sort_order' => $sortOrder,
                'is_active' => true,
            ]
        );

        // 3. Grant to Super Admin role
        $superAdmin = Role::where('name', 'Super Admin')->first();
        if ($superAdmin) {
            $superAdmin->givePermissionTo($spatiePermission);
        }

        $this->command->info("  ✓ Created: {$name}");
    }

    /**
     * Remove all module permissions (for rollback)
     */
    public function rollback(): void
    {
        $this->command->info('Removing Giving Statements permissions...');

        // Remove module permissions
        ModulePermission::where('module_key', self::MODULE_KEY)->delete();

        // Remove Spatie permissions
        foreach (self::PERMISSIONS as $permissionData) {
            $name = $permissionData['name'];
            Permission::where('name', $name)->delete();
            $this->command->info("  ✓ Removed: {$name}");
        }
    }
}
