@extends('layouts.dashboard')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h5 class="m-0 text-header"><i class='bi bi-file-earmark-text'></i> Giving Statements</h5>
                </div>
                <div class="col-sm-6 d-none d-sm-block">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('dashboard/home') }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ url('dashboard/reports') }}">Reports</a></li>
                        <li class="breadcrumb-item active">Giving Statements</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <!-- Stats Cards -->
            <div class="row mb-3">
                <div class="col-md-3">
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h4>{{ number_format($stats['total_generated']) }}</h4>
                            <p>Total Generated</p>
                        </div>
                        <div class="icon"><i class="bi bi-file-earmark-pdf"></i></div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h4>{{ number_format($stats['total_emailed']) }}</h4>
                            <p>Statements Emailed</p>
                        </div>
                        <div class="icon"><i class="bi bi-envelope-check"></i></div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="small-box bg-primary">
                        <div class="inner">
                            <h4>KES {{ number_format($stats['total_amount_reported'], 0) }}</h4>
                            <p>Total Amount Reported</p>
                        </div>
                        <div class="icon"><i class="bi bi-cash-stack"></i></div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h4>{{ number_format($stats['this_month']) }}</h4>
                            <p>This Month</p>
                        </div>
                        <div class="icon"><i class="bi bi-calendar-check"></i></div>
                    </div>
                </div>
            </div>

            <!-- Action Buttons -->
            <div class="row mb-3">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="btn-group" role="group">
                                <a href="{{ url('dashboard/reports/giving-statements/generate') }}" class="btn btn-primary">
                                    <i class="bi bi-plus-lg"></i> Generate Statements
                                </a>
                                <a href="{{ url('dashboard/reports/giving-statements/settings') }}" class="btn btn-outline-secondary">
                                    <i class="bi bi-gear"></i> Settings
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Recent Reports -->
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><i class="bi bi-clock-history"></i> Recent Reports</h3>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Member</th>
                                            <th>Period</th>
                                            <th>Total Amount</th>
                                            <th>Transactions</th>
                                            <th>Delivery</th>
                                            <th>Generated By</th>
                                            <th>Date</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($recentReports as $report)
                                            <tr>
                                                <td>
                                                    <div class="d-flex align-items-center">
                                                        <div class="bg-primary text-white rounded-circle d-flex align-items-center justify-content-center me-2" style="width: 32px; height: 32px; font-size: 12px;">
                                                            @if($report->user)
                                                                {{ strtoupper(substr($report->user->firstname, 0, 1) . substr($report->user->lastname, 0, 1)) }}
                                                            @else
                                                                UN
                                                            @endif
                                                        </div>
                                                        <div>
                                                            <div class="font-weight-bold">{{ $report->user ? $report->user->firstname . ' ' . $report->user->lastname : 'Unknown User' }}</div>
                                                            <small class="text-muted">{{ $report->user?->email ?? '' }}</small>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>
                                                    {{ date('M d', strtotime($report->report_period_from)) }} - {{ date('M d, Y', strtotime($report->report_period_to)) }}
                                                </td>
                                                <td>
                                                    <span class="font-weight-bold text-success">KES {{ number_format($report->total_amount, 2) }}</span>
                                                </td>
                                                <td>{{ number_format($report->transaction_count) }}</td>
                                                <td>
                                                    @if($report->email_sent_to)
                                                        <span class="badge bg-success"><i class="bi bi-envelope"></i> Emailed</span>
                                                    @else
                                                        <span class="badge bg-secondary"><i class="bi bi-download"></i> Download</span>
                                                    @endif
                                                </td>
                                                <td>{{ $report->generatedBy?->firstname ?? 'System' }} {{ $report->generatedBy?->lastname ?? '' }}</td>
                                                <td>{{ $report->created_at->diffForHumans() }}</td>
                                                <td>
                                                    <div class="btn-group btn-group-sm">
                                                        <a href="{{ url('dashboard/reports/giving-statements/download/' . $report->id) }}" class="btn btn-outline-primary" title="Download">
                                                            <i class="bi bi-download"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="8" class="text-center py-4">
                                                    <div class="text-muted">
                                                        <i class="bi bi-inbox" style="font-size: 2rem;"></i>
                                                        <p class="mt-2">No reports generated yet.</p>
                                                        <a href="{{ url('dashboard/reports/giving-statements/generate') }}" class="btn btn-primary btn-sm">
                                                            Generate Your First Statement
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @if($recentReports->count() > 0)
                            <div class="card-footer">
                                <small class="text-muted">Showing {{ $recentReports->count() }} most recent reports</small>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Quick Guide -->
            <div class="row mt-4">
                <div class="col-md-12">
                    <div class="card border-info">
                        <div class="card-header bg-info text-white">
                            <h5 class="mb-0"><i class="bi bi-lightbulb"></i> Quick Guide</h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <h6><i class="bi bi-1-circle text-info"></i> Generate Statement</h6>
                                    <p class="small text-muted">Select a member, date range, and categories to generate a personalized PDF giving statement.</p>
                                </div>
                                <div class="col-md-4">
                                    <h6><i class="bi bi-2-circle text-info"></i> Password Protection</h6>
                                    <p class="small text-muted">Statements can be password-protected using phone number, ID, or custom codes for security.</p>
                                </div>
                                <div class="col-md-4">
                                    <h6><i class="bi bi-3-circle text-info"></i> Email Delivery</h6>
                                    <p class="small text-muted">Email statements directly to members with verified email addresses. Track opens and downloads.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        // Auto-refresh recent reports every 30 seconds
        setInterval(function() {
            location.reload();
        }, 30000);
    });
</script>
@endpush
